"""Create projects table

Revision ID: 3d3fd43150c1
Revises: f533805006ed
Create Date: 2026-06-27 10:11:26.025540

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d3fd43150c1"
down_revision: Union[str, Sequence[str], None] = "f533805006ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Matches the name Postgres generates for an unnamed `ADD UNIQUE (id)`, so
# databases that applied this revision before the name was added still drop the
# constraint they actually have.
USERS_ID_UNIQUE_CONSTRAINT = "users_id_key"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("tagline", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "IDEA", "VALIDATION", "MVP", "BETA", "PRODUCTION", name="projectstage"
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="projectvisibility"),
            nullable=False,
        ),
        sa.Column("tech_stack", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("demo_url", sa.String(length=500), nullable=True),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column("max_team_size", sa.Integer(), nullable=False),
        sa.Column("hiring", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("banner_url", sa.String(length=500), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("applications_count", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    # Autogenerate emitted this because the new FK targets users.id; the column
    # is already the primary key, so the constraint is redundant. It is kept
    # rather than dropped so that databases which already applied this revision
    # do not diverge from ones migrating fresh -- but it is now named, because
    # `drop_constraint(None, ...)` below could not compile.
    op.create_unique_constraint(USERS_ID_UNIQUE_CONSTRAINT, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(USERS_ID_UNIQUE_CONSTRAINT, "users", type_="unique")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
