"""Create hackathon tables

Revision ID: b7f6e5d4c3a2
Revises: 79de7ba3ecfd
Create Date: 2026-07-28 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7f6e5d4c3a2"
down_revision: Union[str, Sequence[str], None] = "79de7ba3ecfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # hackathons
    op.create_table(
        "hackathons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("theme", sa.String(length=200), nullable=True),
        sa.Column("registration_starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("min_team_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("max_team_size", sa.Integer(), server_default="4", nullable=False),
        sa.Column("prize", sa.String(length=300), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "registration_open",
                "in_progress",
                "judging",
                "completed",
                "cancelled",
                name="hackathonstatus",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hackathons_created_by"), "hackathons", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_hackathons_status"), "hackathons", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_hackathons_created_at"), "hackathons", ["created_at"], unique=False
    )

    # hackathon_teams
    op.create_table(
        "hackathon_teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("member_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hackathon_teams_hackathon_id"),
        "hackathon_teams",
        ["hackathon_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_teams_created_by"),
        "hackathon_teams",
        ["created_by"],
        unique=False,
    )

    # hackathon_team_members
    op.create_table(
        "hackathon_team_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("leader", "member", name="teammemberrole"),
            server_default="member",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["hackathon_teams.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_hackathon_team_member"),
    )
    op.create_index(
        op.f("ix_hackathon_team_members_team_id"),
        "hackathon_team_members",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_team_members_user_id"),
        "hackathon_team_members",
        ["user_id"],
        unique=False,
    )

    # hackathon_registrations
    op.create_table(
        "hackathon_registrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "cancelled",
                "waitlisted",
                name="registrationstatus",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("motivation", sa.Text(), nullable=True),
        sa.Column("experience_level", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["team_id"], ["hackathon_teams.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hackathon_id", "user_id", name="uq_hackathon_registration"
        ),
    )
    op.create_index(
        op.f("ix_hackathon_registrations_hackathon_id"),
        "hackathon_registrations",
        ["hackathon_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_registrations_user_id"),
        "hackathon_registrations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_registrations_status"),
        "hackathon_registrations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_registrations_created_at"),
        "hackathon_registrations",
        ["created_at"],
        unique=False,
    )

    # hackathon_submissions
    op.create_table(
        "hackathon_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("demo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "in_review",
                "accepted",
                "rejected",
                name="submissionstatus",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["hackathon_teams.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["submitted_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hackathon_submissions_hackathon_id"),
        "hackathon_submissions",
        ["hackathon_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_submissions_team_id"),
        "hackathon_submissions",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_submissions_status"),
        "hackathon_submissions",
        ["status"],
        unique=False,
    )

    # hackathon_judges
    op.create_table(
        "hackathon_judges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hackathon_id", "user_id", name="uq_hackathon_judge"),
    )
    op.create_index(
        op.f("ix_hackathon_judges_hackathon_id"),
        "hackathon_judges",
        ["hackathon_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_judges_user_id"),
        "hackathon_judges",
        ["user_id"],
        unique=False,
    )

    # hackathon_scores
    op.create_table(
        "hackathon_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("judge_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["hackathon_submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"], ["hackathon_judges.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "judge_id", name="uq_hackathon_score"),
    )
    op.create_index(
        op.f("ix_hackathon_scores_submission_id"),
        "hackathon_scores",
        ["submission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hackathon_scores_judge_id"),
        "hackathon_scores",
        ["judge_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_hackathon_scores_judge_id"), table_name="hackathon_scores")
    op.drop_index(
        op.f("ix_hackathon_scores_submission_id"), table_name="hackathon_scores"
    )
    op.drop_table("hackathon_scores")

    op.drop_index(op.f("ix_hackathon_judges_user_id"), table_name="hackathon_judges")
    op.drop_index(
        op.f("ix_hackathon_judges_hackathon_id"), table_name="hackathon_judges"
    )
    op.drop_table("hackathon_judges")

    op.drop_index(
        op.f("ix_hackathon_submissions_status"), table_name="hackathon_submissions"
    )
    op.drop_index(
        op.f("ix_hackathon_submissions_team_id"), table_name="hackathon_submissions"
    )
    op.drop_index(
        op.f("ix_hackathon_submissions_hackathon_id"),
        table_name="hackathon_submissions",
    )
    op.drop_table("hackathon_submissions")
    # Dropped here rather than next to hackathon_scores: submissionstatus is the
    # status column of hackathon_submissions, so dropping the type while that
    # table still exists fails with
    # `cannot drop type submissionstatus because other objects depend on it`.
    op.execute("DROP TYPE IF EXISTS submissionstatus")

    op.drop_index(
        op.f("ix_hackathon_registrations_created_at"),
        table_name="hackathon_registrations",
    )
    op.drop_index(
        op.f("ix_hackathon_registrations_status"), table_name="hackathon_registrations"
    )
    op.drop_index(
        op.f("ix_hackathon_registrations_user_id"), table_name="hackathon_registrations"
    )
    op.drop_index(
        op.f("ix_hackathon_registrations_hackathon_id"),
        table_name="hackathon_registrations",
    )
    op.drop_table("hackathon_registrations")
    op.execute("DROP TYPE IF EXISTS registrationstatus")

    op.drop_index(
        op.f("ix_hackathon_team_members_user_id"), table_name="hackathon_team_members"
    )
    op.drop_index(
        op.f("ix_hackathon_team_members_team_id"), table_name="hackathon_team_members"
    )
    op.drop_table("hackathon_team_members")
    op.execute("DROP TYPE IF EXISTS teammemberrole")

    op.drop_index(op.f("ix_hackathon_teams_created_by"), table_name="hackathon_teams")
    op.drop_index(op.f("ix_hackathon_teams_hackathon_id"), table_name="hackathon_teams")
    op.drop_table("hackathon_teams")

    op.drop_index(op.f("ix_hackathons_created_at"), table_name="hackathons")
    op.drop_index(op.f("ix_hackathons_status"), table_name="hackathons")
    op.drop_index(op.f("ix_hackathons_created_by"), table_name="hackathons")
    op.drop_table("hackathons")
    op.execute("DROP TYPE IF EXISTS hackathonstatus")

    # ### end Alembic commands ###
