"""create organization members table

Revision ID: e1d173dca5be
Revises: b2c4d6e8f0a1
Create Date: 2026-07-21 02:36:40.625129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e1d173dca5be"
down_revision: Union[str, Sequence[str], None] = "b2c4d6e8f0a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", name="orgmemberrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_organization_member"
        ),
    )
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"),
        "organization_members",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_application_id"),
        "activities",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_builder_flare_id"),
        "activities",
        ["builder_flare_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_created_at"), "activities", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activities_organization_id"),
        "activities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_project_id"), "activities", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_activities_repository_id"),
        "activities",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_created_at"), "applications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_applications_status"), "applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_success"), "audit_logs", ["success"], unique=False
    )
    op.create_index(
        op.f("ix_builder_flares_created_at"),
        "builder_flares",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_builder_flares_featured"), "builder_flares", ["featured"], unique=False
    )
    op.create_index(
        op.f("ix_builder_flares_status"), "builder_flares", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_projects_is_archived"), "projects", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_projects_is_featured"), "projects", ["is_featured"], unique=False
    )
    op.create_index(op.f("ix_projects_stage"), "projects", ["stage"], unique=False)
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_users_is_verified"), "users", ["is_verified"], unique=False
    )
    # ### end Alembic commands ###

    # Programmatic backfill for existing organization and project owners
    import uuid

    # Backfill Organization owners
    conn = op.get_bind()
    orgs = conn.execute(sa.text("SELECT id, owner_id FROM organizations")).fetchall()
    for org_id, owner_id in orgs:
        conn.execute(
            sa.text(
                "INSERT INTO organization_members (id, organization_id, user_id, role, is_active) "
                "VALUES (:id, :org_id, :owner_id, 'owner', true) "
                "ON CONFLICT (organization_id, user_id) DO NOTHING"
            ),
            {"id": uuid.uuid4(), "org_id": org_id, "owner_id": owner_id},
        )

    # Backfill Project owners
    projs = conn.execute(sa.text("SELECT id, owner_id FROM projects")).fetchall()
    for proj_id, owner_id in projs:
        conn.execute(
            sa.text(
                "INSERT INTO project_members (id, project_id, user_id, role, is_active) "
                "VALUES (:id, :proj_id, :owner_id, 'owner', true) "
                "ON CONFLICT (project_id, user_id) DO NOTHING"
            ),
            {"id": uuid.uuid4(), "proj_id": proj_id, "owner_id": owner_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_verified"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.drop_index(op.f("ix_projects_stage"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_featured"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_archived"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_builder_flares_status"), table_name="builder_flares")
    op.drop_index(op.f("ix_builder_flares_featured"), table_name="builder_flares")
    op.drop_index(op.f("ix_builder_flares_created_at"), table_name="builder_flares")
    op.drop_index(op.f("ix_audit_logs_success"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index(op.f("ix_applications_status"), table_name="applications")
    op.drop_index(op.f("ix_applications_created_at"), table_name="applications")
    # These five sit on columns that d87970cbb1e6 removes, and Postgres drops a
    # column's indexes along with the column -- so by the time this downgrade
    # runs they are usually already gone and a plain DROP INDEX raises
    # `index "ix_activities_repository_id" does not exist`.
    #
    # Whether they are still present depends on how far the sibling branch was
    # applied, so the drops are written to tolerate either state.
    for stale_activity_index in (
        "ix_activities_repository_id",
        "ix_activities_project_id",
        "ix_activities_organization_id",
        "ix_activities_builder_flare_id",
        "ix_activities_application_id",
    ):
        op.execute(f"DROP INDEX IF EXISTS {stale_activity_index}")

    # created_at survives the refactor, so this one is a plain drop.
    op.drop_index(op.f("ix_activities_created_at"), table_name="activities")
    op.drop_index(
        op.f("ix_organization_members_user_id"), table_name="organization_members"
    )
    op.drop_index(
        op.f("ix_organization_members_organization_id"),
        table_name="organization_members",
    )
    op.drop_table("organization_members")
    # ### end Alembic commands ###

    # Drop custom Enum type
    sa.Enum("OWNER", "ADMIN", "MEMBER", name="orgmemberrole").drop(op.get_bind())
